
# A python script to make the rpc calls:

# PYTHONUNBUFFERED is bad for performance https://honcho.readthedocs.io/en/latest/using_procfiles.html#buffered-output
demo: PYTHONUNBUFFERED=true python /wd/multiln/bin/demo.py regtest


# clightning nodes:

alice_regtest: sleep 1 ; lightningd --conf=/wd/conf/alice_regtest.conf --lightning-dir=/wd/daemon-data/alice_regtest/

bob_regtest: sleep 1 ; lightningd --conf=/wd/conf/bob_regtest.conf --lightning-dir=/wd/daemon-data/bob_regtest/
