language: bash
services: docker

after_success:
  # Log that the build worked, because we all need some good news
  - echo "Success running multi-ln-demo"

install:
  - make docker-build

script:
  - docker run multilndemo
