language: bash
services: docker

after_success:
  # Log that the build worked, because we all need some good news
  - echo "Success running multi-ln-demo"

jobs:
  include:

    - name: '0 hops, 1 chain (regtest)'
      script:
        - make pydemo-0-hop

    - name: '1 chain hop (regtest -> liquid-regtest)'
      script:
        - make pydemo-1-hop

    - name: '2 chain hops (regtest -> liquid-regtest -> chain_3)'
      script:
        - make pydemo-2-hop

    # - name: 'rustdemo 1 chain hop (regtest -> liquid-regtest)'
    #   script:
    #     - make rsdemo-1-hop
