language: bash
services: docker

after_success:
  # Log that the build worked, because we all need some good news
  - echo "Success running multi-ln-demo"

jobs:
  include:

    - name: '1 chain (regtest) (default make)'
      script:
        - make docker-build ; docker run multilndemo bash -c "bash /wd/regtest-entry-point.sh"
