language: bash
services: docker

after_success:
  # Log that the build worked, because we all need some good news
  - echo "Success running multi-ln-demo"

jobs:
  include:

    - name: '5 chains'
      script:
        - make docker-demo-5-chains

    - name: '1 chain (regtest)'
      script:
        - make docker-demo-regtest

    - name: '2 chains'
      script:
        - make docker-demo-2-chains

    # - name: 'rustdemo 2 chains'
    #   script:
    #     - make docker-rust-2-chains
