language: bash
services: docker

after_success:
  # Log that the build worked, because we all need some good news
  - echo "Success running multi-ln-demo"

jobs:
  include:

    - name: 'Default make (build and run docker)'
      script:
        - make

    - name: 'rustdemo 2 chains'
      script:
        - make docker-build ; docker run multilndemo bash -c "bash /wd/rustdemo-2-chains-entry-point.sh"
