language: bash
services: docker

after_success:
  # Log that the build worked, because we all need some good news
  - echo "Success running multi-ln-demo"

jobs:
  include:

    - name: '1 chain (regtest)'
      script:
        - make docker-run-regtest

    - name: '2 chains'
      script:
        - make docker-run-2-chains"
