
# A python script to make the rpc calls:

rustdemo: /wd/rustdemo/target/release/rustdemo

# bitcoind nodes:

regtest_bitcoind: bitcoind -chain=regtest -conf=/wd/conf/bitcoind.conf -datadir=/wd/daemon-data/regtest_bitcoind/

chain_2_bitcoind: bitcoind -chain=chain_2 -conf=/wd/conf/bitcoind.conf -datadir=/wd/daemon-data/chain_2_bitcoind/


# clightning nodes:

alice_regtest: sleep 1 ; lightningd --conf=/wd/conf/alice_regtest.conf --lightning-dir=/wd/daemon-data/alice_regtest/

bob_regtest: sleep 1 ; lightningd --conf=/wd/conf/bob_regtest.conf --lightning-dir=/wd/daemon-data/bob_regtest/

bob_chain_2: sleep 1 ; lightningd --conf=/wd/conf/bob_chain_2.conf --lightning-dir=/wd/daemon-data/bob_chain_2/

carol_chain_2: sleep 1 ; lightningd --conf=/wd/conf/carol_chain_2.conf --lightning-dir=/wd/daemon-data/carol_chain_2/
