
# A python script to make the rpc calls:

# PYTHONUNBUFFERED is bad for performance https://honcho.readthedocs.io/en/latest/using_procfiles.html#buffered-output
demo: PYTHONUNBUFFERED=true python /wd/multiln/bin/demo.py regtest chain_2

py_gateway: export FLASK_ENV=development export LC_ALL=C.UTF-8 export LANG=C.UTF-8 export FLASK_APP=/wd/py-ln-gateway/py_ln_gateway/app.py ; PYTHONUNBUFFERED=true flask run

gw_update_price: PYTHONUNBUFFERED=true python /wd/py-ln-gateway/py_ln_gateway/cron/update_price.py

gw_clean_pending: PYTHONUNBUFFERED=true python /wd/py-ln-gateway/py_ln_gateway/cron/cleanup_pending_requests.py

# clightning nodes:

alice_regtest: sleep 1 ; lightningd --conf=/wd/conf/alice_regtest.conf --lightning-dir=/wd/daemon-data/alice_regtest/

bob_regtest: sleep 1 ; lightningd --conf=/wd/conf/bob_regtest.conf --lightning-dir=/wd/daemon-data/bob_regtest/

bob_chain_2: sleep 1 ; lightningd --conf=/wd/conf/bob_chain_2.conf --lightning-dir=/wd/daemon-data/bob_chain_2/

carol_chain_2: sleep 1 ; lightningd --conf=/wd/conf/carol_chain_2.conf --lightning-dir=/wd/daemon-data/carol_chain_2/
