version: '3.6'

networks:
  backend-network:
    driver: bridge

services:

  pydemo:
    environment:
# TODO REM PYTHONUNBUFFERED is bad for performance https://honcho.readthedocs.io/en/latest/using_procfiles.html#buffered-output
      PYTHONUNBUFFERED: "true"
    build:
      context: ../
      dockerfile: docker/pydemo.Dockerfile
    command: "python3 /wd/multiln/bin/demo.py ${PYDEMO_HOPS}"
    depends_on:
      - bitcoind_regtest
      - elementsd_liquid_regtest
      - clightning_alice_regtest
      - clightning_bob_regtest
      - clightning_bob_liquid_regtest
      - clightning_carol_liquid_regtest
      - clightning_carol_regtest
      - clightning_david_regtest
      - bob_gateway
    volumes:
      - "clightning_datadir_alice_regtest:/wd/clightning_datadir_alice/regtest"
      - "clightning_datadir_bob_regtest:/wd/clightning_datadir_bob/regtest"
      - "clightning_datadir_bob_liquid_regtest:/wd/clightning_datadir_bob/liquid-regtest"
      - "clightning_datadir_carol_liquid_regtest:/wd/clightning_datadir_carol/liquid-regtest"
      - "clightning_datadir_carol_regtest:/wd/clightning_datadir_carol/regtest"
      - "clightning_datadir_david_regtest:/wd/clightning_datadir_david/regtest"
    networks:
      - backend-network

  rsdemo:
    build:
      context: ../
      dockerfile: docker/rsdemo.Dockerfile
    command: "/wd/rustdemo/target/release/rustdemo"
    depends_on:
      - bitcoind_regtest
      - elementsd_liquid_regtest
      - clightning_alice_regtest
      - clightning_bob_regtest
      - clightning_bob_liquid_regtest
      - clightning_carol_liquid_regtest
      - clightning_carol_regtest
      - clightning_david_regtest
      - bob_gateway
    volumes:
      - "clightning_datadir_alice_regtest:/wd/clightning_datadir_alice/regtest"
      - "clightning_datadir_bob_regtest:/wd/clightning_datadir_bob/regtest"
      - "clightning_datadir_bob_liquid_regtest:/wd/clightning_datadir_bob/liquid-regtest"
      - "clightning_datadir_carol_liquid_regtest:/wd/clightning_datadir_carol/liquid-regtest"
      - "clightning_datadir_carol_regtest:/wd/clightning_datadir_carol/regtest"
      - "clightning_datadir_david_regtest:/wd/clightning_datadir_david/regtest"
    networks:
      - backend-network

  bob_gateway:
    environment:
      PYTHONUNBUFFERED: "true"
      GATEWAY_DB: "postgresql+psycopg2://postgres:password@db_bob:5432/gateway_db"
      PYGATEWAY_CONF: "/wd/conf/bob_gateway.json"
      FLASK_ENV: development
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      FLASK_APP: /wd/py-ln-gateway/py_ln_gateway/app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
    build:
      context: ../
      dockerfile: "docker/py-gateway.Dockerfile"
    entrypoint: "/wd/docker/entrypoint-py-gateway.sh"
    depends_on:
      - db_bob
      - bitcoind_regtest
      - elementsd_liquid_regtest
      - clightning_bob_regtest
      - clightning_bob_liquid_regtest
      - carol_gateway
    volumes:
      - "clightning_datadir_bob_regtest:/wd/clightning_datadir_bob/regtest"
      - "clightning_datadir_bob_liquid_regtest:/wd/clightning_datadir_bob/liquid-regtest"
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - backend-network

  carol_gateway:
    environment:
      PYTHONUNBUFFERED: "true"
      GATEWAY_DB: "postgresql+psycopg2://postgres:password@db_carol:5432/gateway_db"
      PYGATEWAY_CONF: "/wd/conf/carol_gateway.json"
      FLASK_ENV: development
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      FLASK_APP: /wd/py-ln-gateway/py_ln_gateway/app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 6000
    build:
      context: ../
      dockerfile: "docker/py-gateway.Dockerfile"
    entrypoint: "/wd/docker/entrypoint-py-gateway.sh"
    depends_on:
      - db_carol
      - bitcoind_regtest
      - elementsd_liquid_regtest
      - clightning_carol_liquid_regtest
      - clightning_carol_regtest
    volumes:
      - "clightning_datadir_carol_liquid_regtest:/wd/clightning_datadir_carol/liquid-regtest"
      - "clightning_datadir_carol_regtest:/wd/clightning_datadir_carol/regtest"
    ports:
      - "6000:6000"
    expose:
      - "6000"
    networks:
      - backend-network

  bitcoind_regtest:
    build:
      context: ../
      dockerfile: docker/bitcoind.Dockerfile
    command: "bitcoind -chain=regtest -conf=/wd/conf/bitcoind.conf -datadir=/wd/bitcoind_regtest/"
    ports:
      - "18515:18515"
    expose:
      - "18515"
    volumes:
      - "bitcoind_regtest_datadir:/wd/bitcoind_regtest"
    networks:
      - backend-network

  elementsd_liquid_regtest:
    build:
      context: ../
      dockerfile: docker/elementsd.Dockerfile
    command: "elementsd -chain=liquid-regtest -conf=/wd/conf/bitcoind.conf -datadir=/wd/elementsd_liquid-regtest/"
    ports:
      - "18555:18555"
    expose:
      - "18555"
    volumes:
      - "elementsd_liquid_regtest_datadir:/wd/elementsd_liquid-regtest"
    networks:
      - backend-network

  clightning_alice_regtest:
    environment:
      CLN_CMD: ${CLN_CMD}
    build:
      context: ../
      dockerfile: docker/clightning.Dockerfile
    command: "${CLN_CMD} --conf=/wd/conf/alice_regtest.conf --lightning-dir=/wd/clightning_datadir_alice"
    depends_on:
      - bitcoind_regtest
    volumes:
      - "clightning_datadir_alice_regtest:/wd/clightning_datadir_alice/regtest"
    networks:
      - backend-network

  clightning_bob_regtest:
    environment:
      CLN_CMD: ${CLN_CMD}
    depends_on:
      - bitcoind_regtest
    build:
      context: ../
      dockerfile: docker/clightning.Dockerfile
    command: "${CLN_CMD} --conf=/wd/conf/bob_regtest.conf --lightning-dir=/wd/clightning_datadir_bob"
    volumes:
      - "clightning_datadir_bob_regtest:/wd/clightning_datadir_bob/regtest"
    networks:
      - backend-network

  clightning_bob_liquid_regtest:
    environment:
      CLN_CMD: ${CLN_CMD}
    depends_on:
      - elementsd_liquid_regtest
    build:
      context: ../
      dockerfile: docker/clightning.Dockerfile
    command: "${CLN_CMD} --conf=/wd/conf/bob_liquid_regtest.conf --lightning-dir=/wd/clightning_datadir_bob"
    volumes:
      - "clightning_datadir_bob_liquid_regtest:/wd/clightning_datadir_bob/liquid-regtest"
    networks:
      - backend-network

  clightning_carol_liquid_regtest:
    environment:
      CLN_CMD: ${CLN_CMD}
    depends_on:
      - elementsd_liquid_regtest
    build:
      context: ../
      dockerfile: docker/clightning.Dockerfile
    command: "${CLN_CMD} --conf=/wd/conf/carol_liquid_regtest.conf --lightning-dir=/wd/clightning_datadir_carol"
    volumes:
      - "clightning_datadir_carol_liquid_regtest:/wd/clightning_datadir_carol/liquid-regtest"
    networks:
      - backend-network

  clightning_carol_regtest:
    environment:
      CLN_CMD: ${CLN_CMD}
    depends_on:
      - bitcoind_regtest
    build:
      context: ../
      dockerfile: docker/clightning.Dockerfile
    command: "${CLN_CMD} --conf=/wd/conf/carol_regtest.conf --lightning-dir=/wd/clightning_datadir_carol"
    volumes:
      - "clightning_datadir_carol_regtest:/wd/clightning_datadir_carol/regtest"
    networks:
      - backend-network

  clightning_david_regtest:
    environment:
      CLN_CMD: ${CLN_CMD}
    depends_on:
      - bitcoind_regtest
    build:
      context: ../
      dockerfile: docker/clightning.Dockerfile
    command: "${CLN_CMD} --conf=/wd/conf/david_regtest.conf --lightning-dir=/wd/clightning_datadir_david"
    volumes:
      - "clightning_datadir_david_regtest:/wd/clightning_datadir_david/regtest"
    networks:
      - backend-network

  db_bob:
    image: postgres:11.1
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "gateway_db"
    restart: on-failure
    networks:
      - backend-network

  db_carol:
    image: postgres:11.1
    ports:
      - "5433:5432"
    expose:
      - "5433"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "gateway_db"
    restart: on-failure
    networks:
      - backend-network

volumes:
  clightning_datadir_alice_regtest:
  clightning_datadir_bob_regtest:
  clightning_datadir_bob_liquid_regtest:
  clightning_datadir_carol_liquid_regtest:
  clightning_datadir_carol_regtest:
  clightning_datadir_david_regtest:
  bitcoind_regtest_datadir:
  elementsd_liquid_regtest_datadir:
