version: '3.6'

networks:
  backend-network:
    driver: bridge

services:

  demo:
    build:
      context: ../
      dockerfile: docker/py-demo.Dockerfile
    environment:
# PYTHONUNBUFFERED is bad for performance https://honcho.readthedocs.io/en/latest/using_procfiles.html#buffered-output
      PYTHONUNBUFFERED: "true"
    command: "python /wd/multiln/bin/demo.py ${PYDEMO_CHAINS}"
    depends_on:
      - bitcoind_regtest
      - bitcoind_chain_2
      - bitcoind_chain_3
      - lightningds
      - bob_gateway
    volumes:
      - "clightning_alice_regtest_datadir:/wd/daemon-data/alice_regtest"
      - "clightning_bob_regtest_datadir:/wd/daemon-data/bob_regtest"
      - "clightning_bob_chain_2_datadir:/wd/daemon-data/bob_chain_2"
      - "clightning_carol_chain_2_datadir:/wd/daemon-data/carol_chain_2"
      - "clightning_carol_chain_3_datadir:/wd/daemon-data/carol_chain_3"
      - "clightning_david_chain_3_datadir:/wd/daemon-data/david_chain_3"
    networks:
      - backend-network

  bob_gateway:
    build:
      context: ../
      dockerfile: "docker/py-gateway.Dockerfile"
    entrypoint: "/wd/docker/entrypoint-py-gateway.sh"
    depends_on:
      - db
      - bitcoind_regtest
      - bitcoind_chain_2
      - lightningds
    volumes:
      - "clightning_bob_regtest_datadir:/wd/daemon-data/bob_regtest"
      - "clightning_bob_chain_2_datadir:/wd/daemon-data/bob_chain_2"
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - backend-network

  bitcoind_regtest:
    build:
      context: ../
      dockerfile: docker/bitcoind.Dockerfile
    entrypoint: "/wd/docker/entrypoint-bitcoind.sh"
    environment:
      BITCOIND_CALL: "bitcoind -chain=regtest -conf=/wd/conf/bitcoind.conf -datadir=/wd/daemon-data/regtest_bitcoind/"
    ports:
      - "18515:18515"
    expose:
      - "18515"
    networks:
      - backend-network

  bitcoind_chain_2:
    build:
      context: ../
      dockerfile: docker/bitcoind.Dockerfile
    entrypoint: "/wd/docker/entrypoint-bitcoind.sh"
    environment:
      BITCOIND_CALL: "bitcoind -chain=chain_2 -conf=/wd/conf/bitcoind.conf -datadir=/wd/daemon-data/chain_2_bitcoind/"
    ports:
      - "18555:18555"
    expose:
      - "18555"
    networks:
      - backend-network

  bitcoind_chain_3:
    build:
      context: ../
      dockerfile: docker/bitcoind.Dockerfile
    entrypoint: "/wd/docker/entrypoint-bitcoind.sh"
    environment:
      BITCOIND_CALL: "bitcoind -chain=chain_3 -conf=/wd/conf/bitcoind.conf -datadir=/wd/daemon-data/chain_3_bitcoind/"
    ports:
      - "18565:18565"
    expose:
      - "18565"
    networks:
      - backend-network

  lightningds:
    build:
      context: ../
      dockerfile: docker/clightning.Dockerfile
    command: "honcho start -f ${LIGHTNINGD_PROCFILE}"
    depends_on:
      - bitcoind_regtest
      - bitcoind_chain_2
      - bitcoind_chain_3
    volumes:
      - "clightning_alice_regtest_datadir:/wd/daemon-data/alice_regtest"
      - "clightning_bob_regtest_datadir:/wd/daemon-data/bob_regtest"
      - "clightning_bob_chain_2_datadir:/wd/daemon-data/bob_chain_2"
      - "clightning_carol_chain_2_datadir:/wd/daemon-data/carol_chain_2"
      - "clightning_carol_chain_3_datadir:/wd/daemon-data/carol_chain_3"
      - "clightning_david_chain_3_datadir:/wd/daemon-data/david_chain_3"
    networks:
      - backend-network

  db:
    image: postgres:11.1
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gateway_db
    restart: on-failure
    networks:
      - backend-network

volumes:
  clightning_alice_regtest_datadir:
  clightning_bob_regtest_datadir:
  clightning_bob_chain_2_datadir:
  clightning_carol_chain_2_datadir:
  clightning_carol_chain_3_datadir:
  clightning_david_chain_3_datadir:
