version: '3.6'

networks:
  backend-network:
    driver: bridge

services:

  demo:
    build:
      context: ../
      dockerfile: docker/py-demo.Dockerfile
    entrypoint: ${DEMO_ENTRYPOINT}
    depends_on:
      - db
      - bitcoind_regtest
      - daemons
    networks:
      - backend-network

  daemons:
    build:
      context: ../
      dockerfile: docker/bitcoind.Dockerfile
    entrypoint: "/wd/docker/entrypoint-bitcoind.sh"
    environment:
      BITCOIND_PROCFILE: ${BITCOIND_PROCFILE}
    ports:
      - "18555:18555"
      - "18565:18565"
    expose:
      - "18555"
      - "18565"
    networks:
      - backend-network

  bitcoind_regtest:
    build:
      context: ../
      dockerfile: docker/bitcoind.Dockerfile
    entrypoint: "/wd/docker/entrypoint-bitcoind.sh"
    environment:
      BITCOIND_PROCFILE: "/wd/docker/bitcoind_regtest.Procfile"
    ports:
      - "18515:18515"
    expose:
      - "18515"
    networks:
      - backend-network

  db:
    image: postgres:11.1
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gateway_db
    restart: on-failure
    networks:
      - backend-network
