version: '3.6'

networks:
  backend-network:
    driver: bridge

services:

  pydemo:
    environment:
# TODO REM PYTHONUNBUFFERED is bad for performance https://honcho.readthedocs.io/en/latest/using_procfiles.html#buffered-output
      PYTHONUNBUFFERED: "true"
    build:
      context: ../
      dockerfile: docker/pydemo.Dockerfile
    command: "python /wd/multiln/bin/demo.py ${PYDEMO_CHAINS}"
    depends_on:
      - bitcoind_regtest
      - bitcoind_chain_2
      - bitcoind_chain_3
      - clightning_alice_regtest
      - clightning_bob_regtest
      - clightning_bob_chain_2
      - clightning_carol_chain_2
      - clightning_carol_chain_3
      - clightning_david_chain_3
      - bob_gateway
    volumes:
      - "clightning_datadir_alice_regtest:/wd/clightning_datadir_alice_regtest"
      - "clightning_datadir_bob_regtest:/wd/clightning_datadir_bob_regtest"
      - "clightning_datadir_bob_chain_2:/wd/clightning_datadir_bob_chain_2"
      - "clightning_datadir_carol_chain_2:/wd/clightning_datadir_carol_chain_2"
      - "clightning_datadir_carol_chain_3:/wd/clightning_datadir_carol_chain_3"
      - "clightning_datadir_david_chain_3:/wd/clightning_datadir_david_chain_3"
    networks:
      - backend-network

  rsdemo:
    build:
      context: ../
      dockerfile: docker/rsdemo.Dockerfile
    command: "/wd/rustdemo/target/release/rustdemo"
    depends_on:
      - bitcoind_regtest
      - bitcoind_chain_2
      - bitcoind_chain_3
      - clightning_alice_regtest
      - clightning_bob_regtest
      - clightning_bob_chain_2
      - clightning_carol_chain_2
      - clightning_carol_chain_3
      - clightning_david_chain_3
      - bob_gateway
    volumes:
      - "clightning_datadir_alice_regtest:/wd/clightning_datadir_alice_regtest"
      - "clightning_datadir_bob_regtest:/wd/clightning_datadir_bob_regtest"
      - "clightning_datadir_bob_chain_2:/wd/clightning_datadir_bob_chain_2"
      - "clightning_datadir_carol_chain_2:/wd/clightning_datadir_carol_chain_2"
      - "clightning_datadir_carol_chain_3:/wd/clightning_datadir_carol_chain_3"
      - "clightning_datadir_david_chain_3:/wd/clightning_datadir_david_chain_3"
    networks:
      - backend-network

  bob_gateway:
    environment:
      PYTHONUNBUFFERED: "true"
    build:
      context: ../
      dockerfile: "docker/py-gateway.Dockerfile"
    entrypoint: "/wd/docker/entrypoint-py-gateway.sh"
    depends_on:
      - db
      - bitcoind_regtest
      - bitcoind_chain_2
      - clightning_bob_regtest
      - clightning_bob_chain_2
    volumes:
      - "clightning_datadir_bob_regtest:/wd/clightning_datadir_bob_regtest"
      - "clightning_datadir_bob_chain_2:/wd/clightning_datadir_bob_chain_2"
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - backend-network

  bitcoind_regtest:
    build:
      context: ../
      dockerfile: docker/bitcoind.Dockerfile
    command: "bitcoind -chain=regtest -conf=/wd/conf/bitcoind.conf -datadir=/wd/daemon-data/bitcoind_regtest/"
    ports:
      - "18515:18515"
    expose:
      - "18515"
    volumes:
      - "bitcoind_regtest_datadir:/wd/daemon-data/bitcoind_regtest"
    networks:
      - backend-network

  bitcoind_chain_2:
    build:
      context: ../
      dockerfile: docker/bitcoind_custom.Dockerfile
    command: "bitcoind -chain=chain_2 -conf=/wd/conf/bitcoind.conf -datadir=/wd/daemon-data/bitcoind_chain_2/"
    ports:
      - "18555:18555"
    expose:
      - "18555"
    volumes:
      - "bitcoind_chain_2_datadir:/wd/daemon-data/bitcoind_chain_2"
    networks:
      - backend-network

  bitcoind_chain_3:
    build:
      context: ../
      dockerfile: docker/bitcoind_custom.Dockerfile
    command: "bitcoind -chain=chain_3 -conf=/wd/conf/bitcoind.conf -datadir=/wd/daemon-data/bitcoind_chain_3/"
    ports:
      - "18565:18565"
    expose:
      - "18565"
    volumes:
      - "bitcoind_chain_3_datadir:/wd/daemon-data/bitcoind_chain_3"
    networks:
      - backend-network

  clightning_alice_regtest:
    environment:
      PYTHONUNBUFFERED: "true"
    build:
      context: ../
      dockerfile: docker/clightning.Dockerfile
    command: "honcho start -f /wd/docker/clightning/alice_regtest.Procfile"
    depends_on:
      - bitcoind_regtest
    volumes:
      - "clightning_datadir_alice_regtest:/wd/clightning_datadir_alice_regtest"
    networks:
      - backend-network

  clightning_bob_regtest:
    environment:
      PYTHONUNBUFFERED: "true"
    depends_on:
      - bitcoind_regtest
    build:
      context: ../
      dockerfile: docker/clightning.Dockerfile
    command: "honcho start -f /wd/docker/clightning/bob_regtest.Procfile"
    volumes:
      - "clightning_datadir_bob_regtest:/wd/clightning_datadir_bob_regtest"
    networks:
      - backend-network

  clightning_bob_chain_2:
    environment:
      PYTHONUNBUFFERED: "true"
    depends_on:
      - bitcoind_chain_2
    build:
      context: ../
      dockerfile: docker/clightning_custom.Dockerfile
    command: "honcho start -f /wd/docker/clightning/bob_chain_2.Procfile"
    volumes:
      - "clightning_datadir_bob_chain_2:/wd/clightning_datadir_bob_chain_2"
    networks:
      - backend-network

  clightning_carol_chain_2:
    environment:
      PYTHONUNBUFFERED: "true"
    depends_on:
      - bitcoind_chain_2
    build:
      context: ../
      dockerfile: docker/clightning_custom.Dockerfile
    command: "honcho start -f /wd/docker/clightning/carol_chain_2.Procfile"
    volumes:
      - "clightning_datadir_carol_chain_2:/wd/clightning_datadir_carol_chain_2"
    networks:
      - backend-network

  clightning_carol_chain_3:
    environment:
      PYTHONUNBUFFERED: "true"
    depends_on:
      - bitcoind_chain_3
    build:
      context: ../
      dockerfile: docker/clightning_custom.Dockerfile
    command: "honcho start -f /wd/docker/clightning/carol_chain_3.Procfile"
    volumes:
      - "clightning_datadir_carol_chain_3:/wd/clightning_datadir_carol_chain_3"
    networks:
      - backend-network

  clightning_david_chain_3:
    environment:
      PYTHONUNBUFFERED: "true"
    depends_on:
      - bitcoind_chain_3
    build:
      context: ../
      dockerfile: docker/clightning_custom.Dockerfile
    command: "honcho start -f /wd/docker/clightning/david_chain_3.Procfile"
    volumes:
      - "clightning_datadir_david_chain_3:/wd/clightning_datadir_david_chain_3"
    networks:
      - backend-network

  db:
    image: postgres:11.1
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gateway_db
    restart: on-failure
    networks:
      - backend-network

volumes:
  clightning_datadir_alice_regtest:
  clightning_datadir_bob_regtest:
  clightning_datadir_bob_chain_2:
  clightning_datadir_carol_chain_2:
  clightning_datadir_carol_chain_3:
  clightning_datadir_david_chain_3:
  bitcoind_regtest_datadir:
  bitcoind_chain_2_datadir:
  bitcoind_chain_3_datadir:
