
# A python script to make the rpc calls:

# PYTHONUNBUFFERED is bad for performance https://honcho.readthedocs.io/en/latest/using_procfiles.html#buffered-output
demo: PYTHONUNBUFFERED=true python /wd/multiln/bin/demo.py regtest,chain_2,chain_3
