
# A python script to make the rpc calls:

# PYTHONUNBUFFERED is bad for performance https://honcho.readthedocs.io/en/latest/using_procfiles.html#buffered-output
demo: PYTHONUNBUFFERED=true python /wd/multiln/bin/demo.py regtest chain_2 chain_3

py_gateway: export FLASK_ENV=development export LC_ALL=C.UTF-8 export LANG=C.UTF-8 export FLASK_APP=/wd/py-ln-gateway/py_ln_gateway/app.py ; PYTHONUNBUFFERED=true flask run

gw_update_price: PYTHONUNBUFFERED=true python /wd/py-ln-gateway/py_ln_gateway/cron/update_price.py

gw_clean_pending: PYTHONUNBUFFERED=true python /wd/py-ln-gateway/py_ln_gateway/cron/cleanup_pending_requests.py

# bitcoind nodes:

regtest_bitcoind: bitcoind -chain=regtest -conf=/wd/conf/bitcoind.conf -datadir=/wd/daemon-data/regtest_bitcoind/

chain_2_bitcoind: bitcoind -chain=chain_2 -conf=/wd/conf/bitcoind.conf -datadir=/wd/daemon-data/chain_2_bitcoind/

chain_3_bitcoind: bitcoind -chain=chain_3 -conf=/wd/conf/bitcoind.conf -datadir=/wd/daemon-data/chain_3_bitcoind/

# clightning nodes:

alice_regtest: sleep 1 ; lightningd --conf=/wd/conf/alice_regtest.conf --lightning-dir=/wd/daemon-data/alice_regtest/

bob_regtest: sleep 1 ; lightningd --conf=/wd/conf/bob_regtest.conf --lightning-dir=/wd/daemon-data/bob_regtest/

bob_chain_2: sleep 1 ; lightningd --conf=/wd/conf/bob_chain_2.conf --lightning-dir=/wd/daemon-data/bob_chain_2/

carol_chain_2: sleep 1 ; lightningd --conf=/wd/conf/carol_chain_2.conf --lightning-dir=/wd/daemon-data/carol_chain_2/

carol_chain_3: sleep 1 ; lightningd --conf=/wd/conf/carol_chain_3.conf --lightning-dir=/wd/daemon-data/carol_chain_3/

david_chain_3: sleep 1 ; lightningd --conf=/wd/conf/david_chain_3.conf --lightning-dir=/wd/daemon-data/david_chain_3/
